### ISSUE TITLE
Dataset Unavailable

### ISSUE THREAD

**Issue by HeYeshuai** [uta-smile/AAAI2014_Yeqing#1]
Hi, 

Hope you are doing well.
Your program looks great. But it seems like the link of getting Tiny1M_ dataset in get_data.sh is unavailable. Could you share it again? Thank you.

It would be a great honor if you could reply to me at your convenience. Thank you.

**Comment by hehuanma** [comment]
Hi, the dropbox account was deleted. We are so sorry for the inconvenience.

**Comment by HeYeshuai** [comment]
> Hi, the dropbox account was deleted. We are so sorry for the inconvenience.

Do you still have a backup of that Tiny1M_ dataset? Could you share it? Thanks!

**Comment by HeYeshuai** [comment]
> Hi, the dropbox account was deleted. We are so sorry for the inconvenience.

Hi, 

Thank you for your information. Do you still have a backup of that Tiny1M_ dataset? Could you share it? Thanks!

**Comment by hehuanma** [comment]
> > Hi, the dropbox account was deleted. We are so sorry for the inconvenience.
> 
> Hi,
> 
> Thank you for your information. Do you still have a backup of that Tiny1M_ dataset? Could you share it? Thanks!

Sorry we have checked all the backup disks in our lab and also contacted the authors, unfortunately there is no backup for the datasets.

**Comment by HeYeshuai** [comment]
Thank you for your information.
